replicaCount: 1

image:
  repository: vanilladawg/bookstore-api
  tag: latest
  pullPolicy: IfNotPresent

autoscaling:
  enabled: false

serviceAccount:
  create: false
  annotations: {}
  name: "default"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: bookstore.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

env:
  DATABASE_URL: "sqlite:///./books.db"
  LOG_LEVEL: "INFO"
  PAGE_SIZE: "10"
  APP_ENV: "dev"
  HOST: "0.0.0.0"
  PORT: "8080"
  RELOAD: "False"
  ALLOWED_ORIGINS: "*"
  DB_POOL_SIZE: "5"
  DB_MAX_OVERFLOW: "10"
